#!/bin/bash
BASEDIR=$(dirname $0)
echo $BASEDIR
pwd
rosrun xacro xacro.py $BASEDIR/../robots/uv_biped.urdf.xacro > $BASEDIR/../models/uv_biped/uv_biped.urdf
rosrun xacro xacro.py $BASEDIR/../robots/uv_biped_lower.urdf.xacro > $BASEDIR/../models/uv_biped_lower/uv_biped_lower.urdf